### ISSUE TITLE
Mana Input Hatches Voiding Mana

### ISSUE THREAD

**Issue by ZackUmstead** [FTBTeam/FTB-Interactions#712]
## Modpack Version: 
FTB Interactions 1.8.2

## Bug Report:
Modular Diversity Mana Input Hatches will continually accept mana, but the machine (Mana Extrapolator and Infernal Deconglomerator both tested) will not make progress on the craft. Additionally, the mana input will never fill, continually accepting mana even when not running.

## Expected Behavior/Suggestions:
Mana Input Hatches should stop accepting when full.

## Is It Repeatable? Steps to Reproduce: 
1. Start new creative world.
2. Build any mana-accepting modular machine.
3. Point mana spreader at the input hatch and watch it disappear.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
N/A

## Known Fix: 
N/A

**Comment by Saereth** [comment]
this should be fixed in the new MD update

**Comment by ZackUmstead** [comment]
After updating to pack version 1.9, this issue still exists.

**Comment by Saereth** [comment]
reported to bord

**Comment by jiamingc0824** [comment]
Updated to 1.9.1. It is still not working. Even though the mana input hatch mana in them, the machine is not producing mana at all.

![mana](https://user-images.githubusercontent.com/33931383/60392201-a75aec00-9b30-11e9-9c78-3e4be4cec2a7.png)
![2019-06-30_12 12 19](https://user-images.githubusercontent.com/33931383/60392202-a75aec00-9b30-11e9-861a-31d6249673d2.png)
